export const products = [
    {
      id: 1,
      seller_id: 3,
      name: "Cá",
      store_name: "Làm đéo gì có tên",
      price: 20230,
      description: "Mô tả là ăn đéo ngon",
      origin: "đéo biết đây là gì",
      points: 785,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 2,
    },
    {
      id: 2,
      seller_id: 1,
      name: "Thịt bò",
      store_name: "Cửa hàng thịt bò tươi",
      price: 150000,
      description: "Thịt bò nhập khẩu chất lượng cao",
      origin: "Úc",
      points: 500,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 1,
    },
    {
      id: 3,
      seller_id: 2,
      name: "Rau cải xanh",
      store_name: "Rau sạch Đà Lạt",
      price: 25000,
      description: "Rau cải xanh tươi ngon, không hóa chất",
      origin: "Đà Lạt",
      points: 300,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 3,
    },
    {
      id: 4,
      seller_id: 4,
      name: "Táo đỏ",
      store_name: "Trái cây nhập khẩu",
      price: 80000,
      description: "Táo đỏ nhập khẩu từ Mỹ, giòn ngọt",
      origin: "Mỹ",
      points: 400,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 4,
    },
    {
      id: 5,
      seller_id: 5,
      name: "Tôm sú",
      store_name: "Hải sản tươi sống",
      price: 120000,
      description: "Tôm sú tươi sống, đánh bắt trong ngày",
      origin: "Nha Trang",
      points: 600,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 5,
    },
    {
      id: 6,
      seller_id: 6,
      name: "Thịt gà ta",
      store_name: "Gà sạch quê nhà",
      price: 90000,
      description: "Thịt gà ta nuôi thả tự nhiên",
      origin: "Hà Nội",
      points: 450,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 1,
    },
    {
      id: 7,
      seller_id: 7,
      name: "Cá hồi phi lê",
      store_name: "Hải sản nhập khẩu",
      price: 250000,
      description: "Cá hồi phi lê tươi ngon, giàu dinh dưỡng",
      origin: "Na Uy",
      points: 700,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 2,
    },
    {
      id: 8,
      seller_id: 8,
      name: "Bắp cải tím",
      store_name: "Rau sạch Đà Lạt",
      price: 30000,
      description: "Bắp cải tím tươi ngon, giàu vitamin",
      origin: "Đà Lạt",
      points: 320,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 3,
    },
    {
      id: 9,
      seller_id: 9,
      name: "Cam sành",
      store_name: "Trái cây miền Tây",
      price: 40000,
      description: "Cam sành ngọt, mọng nước",
      origin: "Tiền Giang",
      points: 350,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 4,
    },
    {
      id: 10,
      seller_id: 10,
      name: "Mực ống",
      store_name: "Hải sản tươi sống",
      price: 180000,
      description: "Mực ống tươi ngon, thích hợp nướng hoặc hấp",
      origin: "Phú Quốc",
      points: 550,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 5,
    },
    {
      id: 11,
      seller_id: 11,
      name: "Thịt heo ba chỉ",
      store_name: "Thịt heo sạch",
      price: 85000,
      description: "Thịt heo ba chỉ tươi ngon, không chất bảo quản",
      origin: "Bình Dương",
      points: 480,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 1,
    },
    {
      id: 12,
      seller_id: 12,
      name: "Cá thu",
      store_name: "Hải sản tươi sống",
      price: 220000,
      description: "Cá thu tươi ngon, thích hợp chiên hoặc kho",
      origin: "Vũng Tàu",
      points: 620,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 2,
    },
    {
      id: 13,
      seller_id: 13,
      name: "Rau muống",
      store_name: "Rau sạch quê nhà",
      price: 15000,
      description: "Rau muống tươi ngon, không hóa chất",
      origin: "Hà Nam",
      points: 280,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 3,
    },
    {
      id: 14,
      seller_id: 14,
      name: "Dưa hấu",
      store_name: "Trái cây miền Tây",
      price: 20000,
      description: "Dưa hấu ngọt, mọng nước",
      origin: "Long An",
      points: 300,
      image_url: "https://bongon.vn/static/team/2017/1024/15088452186635.jpg",
      category_id: 4,
    },
  ];
  
  export const categories = [
    { id: 1, name: "Thịt" },
    { id: 2, name: "Cá" },
    { id: 3, name: "Rau củ" },
    { id: 4, name: "Trái cây" },
    { id: 5, name: "Hải sản" },
  ];
  